/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FilterObject from './FilterObject';

/**
 * The InputNewFilter model module.
 * @module model/InputNewFilter
 * @version 0.0.1
 */
class InputNewFilter {
    /**
     * Constructs a new <code>InputNewFilter</code>.
     * @alias module:model/InputNewFilter
     * @param filterObject {module:model/FilterObject} 
     */
    constructor(filterObject) { 
        
        InputNewFilter.initialize(this, filterObject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, filterObject) { 
        obj['FilterObject'] = filterObject;
    }

    /**
     * Constructs a <code>InputNewFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InputNewFilter} obj Optional instance to populate.
     * @return {module:model/InputNewFilter} The populated <code>InputNewFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InputNewFilter();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('FilterObject')) {
                obj['FilterObject'] = FilterObject.constructFromObject(data['FilterObject']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InputNewFilter</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InputNewFilter</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InputNewFilter.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // validate the optional field `FilterObject`
        if (data['FilterObject']) { // data not null
          FilterObject.validateJSON(data['FilterObject']);
        }

        return true;
    }


}

InputNewFilter.RequiredProperties = ["FilterObject"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
InputNewFilter.prototype['$schema'] = undefined;

/**
 * @member {module:model/FilterObject} FilterObject
 */
InputNewFilter.prototype['FilterObject'] = undefined;






export default InputNewFilter;

