/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InputGetProof model module.
 * @module model/InputGetProof
 * @version 0.0.1
 */
class InputGetProof {
    /**
     * Constructs a new <code>InputGetProof</code>.
     * @alias module:model/InputGetProof
     * @param address {String} 
     * @param storageKeys {Array.<String>} An array of storage-keys that should be proofed and included
     */
    constructor(address, storageKeys) { 
        
        InputGetProof.initialize(this, address, storageKeys);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, storageKeys) { 
        obj['Address'] = address;
        obj['StorageKeys'] = storageKeys;
    }

    /**
     * Constructs a <code>InputGetProof</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InputGetProof} obj Optional instance to populate.
     * @return {module:model/InputGetProof} The populated <code>InputGetProof</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InputGetProof();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('Address')) {
                obj['Address'] = ApiClient.convertToType(data['Address'], 'String');
            }
            if (data.hasOwnProperty('BlockNumber')) {
                obj['BlockNumber'] = ApiClient.convertToType(data['BlockNumber'], 'String');
            }
            if (data.hasOwnProperty('StorageKeys')) {
                obj['StorageKeys'] = ApiClient.convertToType(data['StorageKeys'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InputGetProof</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InputGetProof</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InputGetProof.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['Address'] && !(typeof data['Address'] === 'string' || data['Address'] instanceof String)) {
            throw new Error("Expected the field `Address` to be a primitive type in the JSON string but got " + data['Address']);
        }
        // ensure the json data is a string
        if (data['BlockNumber'] && !(typeof data['BlockNumber'] === 'string' || data['BlockNumber'] instanceof String)) {
            throw new Error("Expected the field `BlockNumber` to be a primitive type in the JSON string but got " + data['BlockNumber']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['StorageKeys'])) {
            throw new Error("Expected the field `StorageKeys` to be an array in the JSON data but got " + data['StorageKeys']);
        }

        return true;
    }


}

InputGetProof.RequiredProperties = ["Address", "StorageKeys"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
InputGetProof.prototype['$schema'] = undefined;

/**
 * @member {String} Address
 */
InputGetProof.prototype['Address'] = undefined;

/**
 * @member {String} BlockNumber
 * @default 'latest'
 */
InputGetProof.prototype['BlockNumber'] = 'latest';

/**
 * An array of storage-keys that should be proofed and included
 * @member {Array.<String>} StorageKeys
 */
InputGetProof.prototype['StorageKeys'] = undefined;






export default InputGetProof;

