/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InputGetStorageAt model module.
 * @module model/InputGetStorageAt
 * @version 0.0.1
 */
class InputGetStorageAt {
    /**
     * Constructs a new <code>InputGetStorageAt</code>.
     * @alias module:model/InputGetStorageAt
     * @param address {String} The address to check for storage
     * @param blockNumber {String} 
     * @param position {String} The integer of the position in storage
     */
    constructor(address, blockNumber, position) { 
        
        InputGetStorageAt.initialize(this, address, blockNumber, position);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, blockNumber, position) { 
        obj['Address'] = address;
        obj['BlockNumber'] = blockNumber;
        obj['Position'] = position;
    }

    /**
     * Constructs a <code>InputGetStorageAt</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InputGetStorageAt} obj Optional instance to populate.
     * @return {module:model/InputGetStorageAt} The populated <code>InputGetStorageAt</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InputGetStorageAt();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('Address')) {
                obj['Address'] = ApiClient.convertToType(data['Address'], 'String');
            }
            if (data.hasOwnProperty('BlockNumber')) {
                obj['BlockNumber'] = ApiClient.convertToType(data['BlockNumber'], 'String');
            }
            if (data.hasOwnProperty('Position')) {
                obj['Position'] = ApiClient.convertToType(data['Position'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InputGetStorageAt</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InputGetStorageAt</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InputGetStorageAt.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['Address'] && !(typeof data['Address'] === 'string' || data['Address'] instanceof String)) {
            throw new Error("Expected the field `Address` to be a primitive type in the JSON string but got " + data['Address']);
        }
        // ensure the json data is a string
        if (data['BlockNumber'] && !(typeof data['BlockNumber'] === 'string' || data['BlockNumber'] instanceof String)) {
            throw new Error("Expected the field `BlockNumber` to be a primitive type in the JSON string but got " + data['BlockNumber']);
        }
        // ensure the json data is a string
        if (data['Position'] && !(typeof data['Position'] === 'string' || data['Position'] instanceof String)) {
            throw new Error("Expected the field `Position` to be a primitive type in the JSON string but got " + data['Position']);
        }

        return true;
    }


}

InputGetStorageAt.RequiredProperties = ["Address", "BlockNumber", "Position"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
InputGetStorageAt.prototype['$schema'] = undefined;

/**
 * The address to check for storage
 * @member {String} Address
 */
InputGetStorageAt.prototype['Address'] = undefined;

/**
 * @member {String} BlockNumber
 */
InputGetStorageAt.prototype['BlockNumber'] = undefined;

/**
 * The integer of the position in storage
 * @member {String} Position
 */
InputGetStorageAt.prototype['Position'] = undefined;






export default InputGetStorageAt;

