/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParamsTransaction from './ParamsTransaction';

/**
 * The InputCall model module.
 * @module model/InputCall
 * @version 0.0.1
 */
class InputCall {
    /**
     * Constructs a new <code>InputCall</code>.
     * @alias module:model/InputCall
     * @param blockNumber {String} 
     * @param transaction {module:model/ParamsTransaction} The transaction call object
     */
    constructor(blockNumber, transaction) { 
        
        InputCall.initialize(this, blockNumber, transaction);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, blockNumber, transaction) { 
        obj['BlockNumber'] = blockNumber;
        obj['Transaction'] = transaction;
    }

    /**
     * Constructs a <code>InputCall</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InputCall} obj Optional instance to populate.
     * @return {module:model/InputCall} The populated <code>InputCall</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InputCall();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('BlockNumber')) {
                obj['BlockNumber'] = ApiClient.convertToType(data['BlockNumber'], 'String');
            }
            if (data.hasOwnProperty('Transaction')) {
                obj['Transaction'] = ParamsTransaction.constructFromObject(data['Transaction']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InputCall</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InputCall</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InputCall.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['BlockNumber'] && !(typeof data['BlockNumber'] === 'string' || data['BlockNumber'] instanceof String)) {
            throw new Error("Expected the field `BlockNumber` to be a primitive type in the JSON string but got " + data['BlockNumber']);
        }
        // validate the optional field `Transaction`
        if (data['Transaction']) { // data not null
          ParamsTransaction.validateJSON(data['Transaction']);
        }

        return true;
    }


}

InputCall.RequiredProperties = ["BlockNumber", "Transaction"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
InputCall.prototype['$schema'] = undefined;

/**
 * @member {String} BlockNumber
 */
InputCall.prototype['BlockNumber'] = undefined;

/**
 * The transaction call object
 * @member {module:model/ParamsTransaction} Transaction
 */
InputCall.prototype['Transaction'] = undefined;






export default InputCall;

