/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EstimateGasObject from './EstimateGasObject';
import ParamsTransaction from './ParamsTransaction';

/**
 * The InputEstimateGas model module.
 * @module model/InputEstimateGas
 * @version 0.0.1
 */
class InputEstimateGas {
    /**
     * Constructs a new <code>InputEstimateGas</code>.
     * @alias module:model/InputEstimateGas
     * @param transaction {module:model/ParamsTransaction} The transaction call object
     */
    constructor(transaction) { 
        
        InputEstimateGas.initialize(this, transaction);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transaction) { 
        obj['Transaction'] = transaction;
    }

    /**
     * Constructs a <code>InputEstimateGas</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InputEstimateGas} obj Optional instance to populate.
     * @return {module:model/InputEstimateGas} The populated <code>InputEstimateGas</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InputEstimateGas();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('Object')) {
                obj['Object'] = EstimateGasObject.constructFromObject(data['Object']);
            }
            if (data.hasOwnProperty('Transaction')) {
                obj['Transaction'] = ParamsTransaction.constructFromObject(data['Transaction']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InputEstimateGas</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InputEstimateGas</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InputEstimateGas.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // validate the optional field `Object`
        if (data['Object']) { // data not null
          EstimateGasObject.validateJSON(data['Object']);
        }
        // validate the optional field `Transaction`
        if (data['Transaction']) { // data not null
          ParamsTransaction.validateJSON(data['Transaction']);
        }

        return true;
    }


}

InputEstimateGas.RequiredProperties = ["Transaction"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
InputEstimateGas.prototype['$schema'] = undefined;

/**
 * The state override set with address-to-state mapping where each address maps to an object containing
 * @member {module:model/EstimateGasObject} Object
 */
InputEstimateGas.prototype['Object'] = undefined;

/**
 * The transaction call object
 * @member {module:model/ParamsTransaction} Transaction
 */
InputEstimateGas.prototype['Transaction'] = undefined;






export default InputEstimateGas;

