/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputChainId model module.
 * @module model/OutputChainId
 * @version 0.0.1
 */
class OutputChainId {
    /**
     * Constructs a new <code>OutputChainId</code>.
     * @alias module:model/OutputChainId
     * @param chainId {String} A decimal value in string format which represents an integer of the chain ID
     */
    constructor(chainId) { 
        
        OutputChainId.initialize(this, chainId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, chainId) { 
        obj['ChainId'] = chainId;
    }

    /**
     * Constructs a <code>OutputChainId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputChainId} obj Optional instance to populate.
     * @return {module:model/OutputChainId} The populated <code>OutputChainId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputChainId();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('ChainId')) {
                obj['ChainId'] = ApiClient.convertToType(data['ChainId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputChainId</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputChainId</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputChainId.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['ChainId'] && !(typeof data['ChainId'] === 'string' || data['ChainId'] instanceof String)) {
            throw new Error("Expected the field `ChainId` to be a primitive type in the JSON string but got " + data['ChainId']);
        }

        return true;
    }


}

OutputChainId.RequiredProperties = ["ChainId"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputChainId.prototype['$schema'] = undefined;

/**
 * A decimal value in string format which represents an integer of the chain ID
 * @member {String} ChainId
 */
OutputChainId.prototype['ChainId'] = undefined;






export default OutputChainId;

