/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputGetCode model module.
 * @module model/OutputGetCode
 * @version 0.0.1
 */
class OutputGetCode {
    /**
     * Constructs a new <code>OutputGetCode</code>.
     * @alias module:model/OutputGetCode
     * @param bytecode {String} The bytecode from a given address
     */
    constructor(bytecode) { 
        
        OutputGetCode.initialize(this, bytecode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, bytecode) { 
        obj['Bytecode'] = bytecode;
    }

    /**
     * Constructs a <code>OutputGetCode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputGetCode} obj Optional instance to populate.
     * @return {module:model/OutputGetCode} The populated <code>OutputGetCode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputGetCode();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('Bytecode')) {
                obj['Bytecode'] = ApiClient.convertToType(data['Bytecode'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputGetCode</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputGetCode</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputGetCode.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['Bytecode'] && !(typeof data['Bytecode'] === 'string' || data['Bytecode'] instanceof String)) {
            throw new Error("Expected the field `Bytecode` to be a primitive type in the JSON string but got " + data['Bytecode']);
        }

        return true;
    }


}

OutputGetCode.RequiredProperties = ["Bytecode"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputGetCode.prototype['$schema'] = undefined;

/**
 * The bytecode from a given address
 * @member {String} Bytecode
 */
OutputGetCode.prototype['Bytecode'] = undefined;






export default OutputGetCode;

