/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseLog from './ResponseLog';

/**
 * The OutputGetFilterLogs model module.
 * @module model/OutputGetFilterLogs
 * @version 0.0.1
 */
class OutputGetFilterLogs {
    /**
     * Constructs a new <code>OutputGetFilterLogs</code>.
     * @alias module:model/OutputGetFilterLogs
     * @param logs {Array.<module:model/ResponseLog>} An array of log objects, or an empty array if nothing has changed since last poll
     */
    constructor(logs) { 
        
        OutputGetFilterLogs.initialize(this, logs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, logs) { 
        obj['Logs'] = logs;
    }

    /**
     * Constructs a <code>OutputGetFilterLogs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputGetFilterLogs} obj Optional instance to populate.
     * @return {module:model/OutputGetFilterLogs} The populated <code>OutputGetFilterLogs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputGetFilterLogs();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('Logs')) {
                obj['Logs'] = ApiClient.convertToType(data['Logs'], [ResponseLog]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputGetFilterLogs</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputGetFilterLogs</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputGetFilterLogs.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        if (data['Logs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Logs'])) {
                throw new Error("Expected the field `Logs` to be an array in the JSON data but got " + data['Logs']);
            }
            // validate the optional field `Logs` (array)
            for (const item of data['Logs']) {
                ResponseLog.validateJSON(item);
            };
        }

        return true;
    }


}

OutputGetFilterLogs.RequiredProperties = ["Logs"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputGetFilterLogs.prototype['$schema'] = undefined;

/**
 * An array of log objects, or an empty array if nothing has changed since last poll
 * @member {Array.<module:model/ResponseLog>} Logs
 */
OutputGetFilterLogs.prototype['Logs'] = undefined;






export default OutputGetFilterLogs;

