/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SyncStatus from './SyncStatus';

/**
 * The OutputSyncing model module.
 * @module model/OutputSyncing
 * @version 0.0.1
 */
class OutputSyncing {
    /**
     * Constructs a new <code>OutputSyncing</code>.
     * @alias module:model/OutputSyncing
     * @param syncStatus {module:model/SyncStatus} Returns null when the node is fully synchronized, otherwise returns the sync status
     */
    constructor(syncStatus) { 
        
        OutputSyncing.initialize(this, syncStatus);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, syncStatus) { 
        obj['SyncStatus'] = syncStatus;
    }

    /**
     * Constructs a <code>OutputSyncing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputSyncing} obj Optional instance to populate.
     * @return {module:model/OutputSyncing} The populated <code>OutputSyncing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputSyncing();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('SyncStatus')) {
                obj['SyncStatus'] = SyncStatus.constructFromObject(data['SyncStatus']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputSyncing</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputSyncing</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputSyncing.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // validate the optional field `SyncStatus`
        if (data['SyncStatus']) { // data not null
          SyncStatus.validateJSON(data['SyncStatus']);
        }

        return true;
    }


}

OutputSyncing.RequiredProperties = ["SyncStatus"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputSyncing.prototype['$schema'] = undefined;

/**
 * Returns null when the node is fully synchronized, otherwise returns the sync status
 * @member {module:model/SyncStatus} SyncStatus
 */
OutputSyncing.prototype['SyncStatus'] = undefined;






export default OutputSyncing;

