/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputBlockNumber model module.
 * @module model/OutputBlockNumber
 * @version 0.0.1
 */
class OutputBlockNumber {
    /**
     * Constructs a new <code>OutputBlockNumber</code>.
     * @alias module:model/OutputBlockNumber
     * @param blockNumber {String} An integer value of the latest block number encoded as decimal
     */
    constructor(blockNumber) { 
        
        OutputBlockNumber.initialize(this, blockNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, blockNumber) { 
        obj['BlockNumber'] = blockNumber;
    }

    /**
     * Constructs a <code>OutputBlockNumber</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputBlockNumber} obj Optional instance to populate.
     * @return {module:model/OutputBlockNumber} The populated <code>OutputBlockNumber</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputBlockNumber();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('BlockNumber')) {
                obj['BlockNumber'] = ApiClient.convertToType(data['BlockNumber'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputBlockNumber</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputBlockNumber</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputBlockNumber.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['BlockNumber'] && !(typeof data['BlockNumber'] === 'string' || data['BlockNumber'] instanceof String)) {
            throw new Error("Expected the field `BlockNumber` to be a primitive type in the JSON string but got " + data['BlockNumber']);
        }

        return true;
    }


}

OutputBlockNumber.RequiredProperties = ["BlockNumber"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputBlockNumber.prototype['$schema'] = undefined;

/**
 * An integer value of the latest block number encoded as decimal
 * @member {String} BlockNumber
 */
OutputBlockNumber.prototype['BlockNumber'] = undefined;






export default OutputBlockNumber;

