/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputEstimateGas model module.
 * @module model/OutputEstimateGas
 * @version 0.0.1
 */
class OutputEstimateGas {
    /**
     * Constructs a new <code>OutputEstimateGas</code>.
     * @alias module:model/OutputEstimateGas
     * @param estimatedGas {String} The estimated amount of gas used
     */
    constructor(estimatedGas) { 
        
        OutputEstimateGas.initialize(this, estimatedGas);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, estimatedGas) { 
        obj['EstimatedGas'] = estimatedGas;
    }

    /**
     * Constructs a <code>OutputEstimateGas</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputEstimateGas} obj Optional instance to populate.
     * @return {module:model/OutputEstimateGas} The populated <code>OutputEstimateGas</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputEstimateGas();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('EstimatedGas')) {
                obj['EstimatedGas'] = ApiClient.convertToType(data['EstimatedGas'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputEstimateGas</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputEstimateGas</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputEstimateGas.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['EstimatedGas'] && !(typeof data['EstimatedGas'] === 'string' || data['EstimatedGas'] instanceof String)) {
            throw new Error("Expected the field `EstimatedGas` to be a primitive type in the JSON string but got " + data['EstimatedGas']);
        }

        return true;
    }


}

OutputEstimateGas.RequiredProperties = ["EstimatedGas"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputEstimateGas.prototype['$schema'] = undefined;

/**
 * The estimated amount of gas used
 * @member {String} EstimatedGas
 */
OutputEstimateGas.prototype['EstimatedGas'] = undefined;






export default OutputEstimateGas;

