/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputSubscribe model module.
 * @module model/OutputSubscribe
 * @version 0.0.1
 */
class OutputSubscribe {
    /**
     * Constructs a new <code>OutputSubscribe</code>.
     * @alias module:model/OutputSubscribe
     * @param subscriptionId {String} The hex encoded subscription ID. This ID will be attached to all received events and can also be used to cancel the subscription using eth_unsubscribe
     */
    constructor(subscriptionId) { 
        
        OutputSubscribe.initialize(this, subscriptionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, subscriptionId) { 
        obj['SubscriptionId'] = subscriptionId;
    }

    /**
     * Constructs a <code>OutputSubscribe</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputSubscribe} obj Optional instance to populate.
     * @return {module:model/OutputSubscribe} The populated <code>OutputSubscribe</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputSubscribe();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('SubscriptionId')) {
                obj['SubscriptionId'] = ApiClient.convertToType(data['SubscriptionId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputSubscribe</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputSubscribe</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputSubscribe.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['SubscriptionId'] && !(typeof data['SubscriptionId'] === 'string' || data['SubscriptionId'] instanceof String)) {
            throw new Error("Expected the field `SubscriptionId` to be a primitive type in the JSON string but got " + data['SubscriptionId']);
        }

        return true;
    }


}

OutputSubscribe.RequiredProperties = ["SubscriptionId"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputSubscribe.prototype['$schema'] = undefined;

/**
 * The hex encoded subscription ID. This ID will be attached to all received events and can also be used to cancel the subscription using eth_unsubscribe
 * @member {String} SubscriptionId
 */
OutputSubscribe.prototype['SubscriptionId'] = undefined;






export default OutputSubscribe;

