/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseTransactionReceipt from './ResponseTransactionReceipt';

/**
 * The OutputGetBlockReceipts model module.
 * @module model/OutputGetBlockReceipts
 * @version 0.0.1
 */
class OutputGetBlockReceipts {
    /**
     * Constructs a new <code>OutputGetBlockReceipts</code>.
     * @alias module:model/OutputGetBlockReceipts
     * @param transactionReceipts {Array.<module:model/ResponseTransactionReceipt>} An array of transaction receipt objects
     */
    constructor(transactionReceipts) { 
        
        OutputGetBlockReceipts.initialize(this, transactionReceipts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transactionReceipts) { 
        obj['TransactionReceipts'] = transactionReceipts;
    }

    /**
     * Constructs a <code>OutputGetBlockReceipts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputGetBlockReceipts} obj Optional instance to populate.
     * @return {module:model/OutputGetBlockReceipts} The populated <code>OutputGetBlockReceipts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputGetBlockReceipts();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('TransactionReceipts')) {
                obj['TransactionReceipts'] = ApiClient.convertToType(data['TransactionReceipts'], [ResponseTransactionReceipt]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputGetBlockReceipts</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputGetBlockReceipts</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputGetBlockReceipts.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        if (data['TransactionReceipts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['TransactionReceipts'])) {
                throw new Error("Expected the field `TransactionReceipts` to be an array in the JSON data but got " + data['TransactionReceipts']);
            }
            // validate the optional field `TransactionReceipts` (array)
            for (const item of data['TransactionReceipts']) {
                ResponseTransactionReceipt.validateJSON(item);
            };
        }

        return true;
    }


}

OutputGetBlockReceipts.RequiredProperties = ["TransactionReceipts"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputGetBlockReceipts.prototype['$schema'] = undefined;

/**
 * An array of transaction receipt objects
 * @member {Array.<module:model/ResponseTransactionReceipt>} TransactionReceipts
 */
OutputGetBlockReceipts.prototype['TransactionReceipts'] = undefined;






export default OutputGetBlockReceipts;

