/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputGasPrice model module.
 * @module model/OutputGasPrice
 * @version 0.0.1
 */
class OutputGasPrice {
    /**
     * Constructs a new <code>OutputGasPrice</code>.
     * @alias module:model/OutputGasPrice
     * @param gasPrice {String} The decimal value of the current gas price in wei
     */
    constructor(gasPrice) { 
        
        OutputGasPrice.initialize(this, gasPrice);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gasPrice) { 
        obj['GasPrice'] = gasPrice;
    }

    /**
     * Constructs a <code>OutputGasPrice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputGasPrice} obj Optional instance to populate.
     * @return {module:model/OutputGasPrice} The populated <code>OutputGasPrice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputGasPrice();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('GasPrice')) {
                obj['GasPrice'] = ApiClient.convertToType(data['GasPrice'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputGasPrice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputGasPrice</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputGasPrice.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['GasPrice'] && !(typeof data['GasPrice'] === 'string' || data['GasPrice'] instanceof String)) {
            throw new Error("Expected the field `GasPrice` to be a primitive type in the JSON string but got " + data['GasPrice']);
        }

        return true;
    }


}

OutputGasPrice.RequiredProperties = ["GasPrice"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputGasPrice.prototype['$schema'] = undefined;

/**
 * The decimal value of the current gas price in wei
 * @member {String} GasPrice
 */
OutputGasPrice.prototype['GasPrice'] = undefined;






export default OutputGasPrice;

