/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseTransactionReceipt from './ResponseTransactionReceipt';

/**
 * The OutputGetTransactionReceipt model module.
 * @module model/OutputGetTransactionReceipt
 * @version 0.0.1
 */
class OutputGetTransactionReceipt {
    /**
     * Constructs a new <code>OutputGetTransactionReceipt</code>.
     * @alias module:model/OutputGetTransactionReceipt
     * @param transactionReceipt {module:model/ResponseTransactionReceipt} A transaction receipt object, or null when the transaction is not available
     */
    constructor(transactionReceipt) { 
        
        OutputGetTransactionReceipt.initialize(this, transactionReceipt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transactionReceipt) { 
        obj['TransactionReceipt'] = transactionReceipt;
    }

    /**
     * Constructs a <code>OutputGetTransactionReceipt</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputGetTransactionReceipt} obj Optional instance to populate.
     * @return {module:model/OutputGetTransactionReceipt} The populated <code>OutputGetTransactionReceipt</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputGetTransactionReceipt();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('TransactionReceipt')) {
                obj['TransactionReceipt'] = ResponseTransactionReceipt.constructFromObject(data['TransactionReceipt']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputGetTransactionReceipt</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputGetTransactionReceipt</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputGetTransactionReceipt.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // validate the optional field `TransactionReceipt`
        if (data['TransactionReceipt']) { // data not null
          ResponseTransactionReceipt.validateJSON(data['TransactionReceipt']);
        }

        return true;
    }


}

OutputGetTransactionReceipt.RequiredProperties = ["TransactionReceipt"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputGetTransactionReceipt.prototype['$schema'] = undefined;

/**
 * A transaction receipt object, or null when the transaction is not available
 * @member {module:model/ResponseTransactionReceipt} TransactionReceipt
 */
OutputGetTransactionReceipt.prototype['TransactionReceipt'] = undefined;






export default OutputGetTransactionReceipt;

