/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputBlobBaseFee model module.
 * @module model/OutputBlobBaseFee
 * @version 0.0.1
 */
class OutputBlobBaseFee {
    /**
     * Constructs a new <code>OutputBlobBaseFee</code>.
     * @alias module:model/OutputBlobBaseFee
     * @param baseFee {String} The expected base fee in wei, represented in decimal format
     */
    constructor(baseFee) { 
        
        OutputBlobBaseFee.initialize(this, baseFee);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, baseFee) { 
        obj['BaseFee'] = baseFee;
    }

    /**
     * Constructs a <code>OutputBlobBaseFee</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputBlobBaseFee} obj Optional instance to populate.
     * @return {module:model/OutputBlobBaseFee} The populated <code>OutputBlobBaseFee</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputBlobBaseFee();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('BaseFee')) {
                obj['BaseFee'] = ApiClient.convertToType(data['BaseFee'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputBlobBaseFee</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputBlobBaseFee</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputBlobBaseFee.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['BaseFee'] && !(typeof data['BaseFee'] === 'string' || data['BaseFee'] instanceof String)) {
            throw new Error("Expected the field `BaseFee` to be a primitive type in the JSON string but got " + data['BaseFee']);
        }

        return true;
    }


}

OutputBlobBaseFee.RequiredProperties = ["BaseFee"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputBlobBaseFee.prototype['$schema'] = undefined;

/**
 * The expected base fee in wei, represented in decimal format
 * @member {String} BaseFee
 */
OutputBlobBaseFee.prototype['BaseFee'] = undefined;






export default OutputBlobBaseFee;

