/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputGetBalance model module.
 * @module model/OutputGetBalance
 * @version 0.0.1
 */
class OutputGetBalance {
    /**
     * Constructs a new <code>OutputGetBalance</code>.
     * @alias module:model/OutputGetBalance
     * @param balance {String} The ETH balance of the specified address in decimal value, measured in wei
     */
    constructor(balance) { 
        
        OutputGetBalance.initialize(this, balance);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, balance) { 
        obj['Balance'] = balance;
    }

    /**
     * Constructs a <code>OutputGetBalance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutputGetBalance} obj Optional instance to populate.
     * @return {module:model/OutputGetBalance} The populated <code>OutputGetBalance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputGetBalance();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('Balance')) {
                obj['Balance'] = ApiClient.convertToType(data['Balance'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputGetBalance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputGetBalance</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputGetBalance.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['Balance'] && !(typeof data['Balance'] === 'string' || data['Balance'] instanceof String)) {
            throw new Error("Expected the field `Balance` to be a primitive type in the JSON string but got " + data['Balance']);
        }

        return true;
    }


}

OutputGetBalance.RequiredProperties = ["Balance"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputGetBalance.prototype['$schema'] = undefined;

/**
 * The ETH balance of the specified address in decimal value, measured in wei
 * @member {String} Balance
 */
OutputGetBalance.prototype['Balance'] = undefined;






export default OutputGetBalance;

