/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QanXlinkValidResponse model module.
 * @module model/QanXlinkValidResponse
 * @version 0.0.1
 */
class QanXlinkValidResponse {
    /**
     * Constructs a new <code>QanXlinkValidResponse</code>.
     * @alias module:model/QanXlinkValidResponse
     */
    constructor() { 
        
        QanXlinkValidResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QanXlinkValidResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QanXlinkValidResponse} obj Optional instance to populate.
     * @return {module:model/QanXlinkValidResponse} The populated <code>QanXlinkValidResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QanXlinkValidResponse();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QanXlinkValidResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QanXlinkValidResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }

        return true;
    }


}



/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
QanXlinkValidResponse.prototype['$schema'] = undefined;






export default QanXlinkValidResponse;

