/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SyncStatus model module.
 * @module model/SyncStatus
 * @version 0.0.1
 */
class SyncStatus {
    /**
     * Constructs a new <code>SyncStatus</code>.
     * @alias module:model/SyncStatus
     * @param currentBlock {String} The current block, same as eth_blockNumber encoded as decimal
     * @param highestBlock {String} The estimated highest block encoded as decimal
     * @param startingBlock {String} The block at which the import started encoded as decimal
     */
    constructor(currentBlock, highestBlock, startingBlock) { 
        
        SyncStatus.initialize(this, currentBlock, highestBlock, startingBlock);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currentBlock, highestBlock, startingBlock) { 
        obj['CurrentBlock'] = currentBlock;
        obj['HighestBlock'] = highestBlock;
        obj['StartingBlock'] = startingBlock;
    }

    /**
     * Constructs a <code>SyncStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SyncStatus} obj Optional instance to populate.
     * @return {module:model/SyncStatus} The populated <code>SyncStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SyncStatus();

            if (data.hasOwnProperty('CurrentBlock')) {
                obj['CurrentBlock'] = ApiClient.convertToType(data['CurrentBlock'], 'String');
            }
            if (data.hasOwnProperty('HighestBlock')) {
                obj['HighestBlock'] = ApiClient.convertToType(data['HighestBlock'], 'String');
            }
            if (data.hasOwnProperty('StartingBlock')) {
                obj['StartingBlock'] = ApiClient.convertToType(data['StartingBlock'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SyncStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SyncStatus</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SyncStatus.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['CurrentBlock'] && !(typeof data['CurrentBlock'] === 'string' || data['CurrentBlock'] instanceof String)) {
            throw new Error("Expected the field `CurrentBlock` to be a primitive type in the JSON string but got " + data['CurrentBlock']);
        }
        // ensure the json data is a string
        if (data['HighestBlock'] && !(typeof data['HighestBlock'] === 'string' || data['HighestBlock'] instanceof String)) {
            throw new Error("Expected the field `HighestBlock` to be a primitive type in the JSON string but got " + data['HighestBlock']);
        }
        // ensure the json data is a string
        if (data['StartingBlock'] && !(typeof data['StartingBlock'] === 'string' || data['StartingBlock'] instanceof String)) {
            throw new Error("Expected the field `StartingBlock` to be a primitive type in the JSON string but got " + data['StartingBlock']);
        }

        return true;
    }


}

SyncStatus.RequiredProperties = ["CurrentBlock", "HighestBlock", "StartingBlock"];

/**
 * The current block, same as eth_blockNumber encoded as decimal
 * @member {String} CurrentBlock
 */
SyncStatus.prototype['CurrentBlock'] = undefined;

/**
 * The estimated highest block encoded as decimal
 * @member {String} HighestBlock
 */
SyncStatus.prototype['HighestBlock'] = undefined;

/**
 * The block at which the import started encoded as decimal
 * @member {String} StartingBlock
 */
SyncStatus.prototype['StartingBlock'] = undefined;






export default SyncStatus;

