/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QanAutoApi);
  }
}(this, function(expect, QanAutoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QanAutoApi.ResponseLog();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseLog', function() {
    it('should create an instance of ResponseLog', function() {
      // uncomment below and update the code to test ResponseLog
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be.a(QanAutoApi.ResponseLog);
    });

    it('should have the property address (base name: "Address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be();
    });

    it('should have the property blockHash (base name: "BlockHash")', function() {
      // uncomment below and update the code to test the property blockHash
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be();
    });

    it('should have the property blockNumber (base name: "BlockNumber")', function() {
      // uncomment below and update the code to test the property blockNumber
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "Data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be();
    });

    it('should have the property logIndex (base name: "LogIndex")', function() {
      // uncomment below and update the code to test the property logIndex
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be();
    });

    it('should have the property removed (base name: "Removed")', function() {
      // uncomment below and update the code to test the property removed
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be();
    });

    it('should have the property topics (base name: "Topics")', function() {
      // uncomment below and update the code to test the property topics
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be();
    });

    it('should have the property transactionHash (base name: "TransactionHash")', function() {
      // uncomment below and update the code to test the property transactionHash
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be();
    });

    it('should have the property transactionIndex (base name: "TransactionIndex")', function() {
      // uncomment below and update the code to test the property transactionIndex
      //var instance = new QanAutoApi.ResponseLog();
      //expect(instance).to.be();
    });

  });

}));
