/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QanAutoApi);
  }
}(this, function(expect, QanAutoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QanAutoApi.ResponseTransactionReceipt();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseTransactionReceipt', function() {
    it('should create an instance of ResponseTransactionReceipt', function() {
      // uncomment below and update the code to test ResponseTransactionReceipt
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be.a(QanAutoApi.ResponseTransactionReceipt);
    });

    it('should have the property blockHash (base name: "BlockHash")', function() {
      // uncomment below and update the code to test the property blockHash
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property blockNumber (base name: "BlockNumber")', function() {
      // uncomment below and update the code to test the property blockNumber
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property contractAddress (base name: "ContractAddress")', function() {
      // uncomment below and update the code to test the property contractAddress
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property cumulativeGasUsed (base name: "CumulativeGasUsed")', function() {
      // uncomment below and update the code to test the property cumulativeGasUsed
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property effectiveGasPrice (base name: "EffectiveGasPrice")', function() {
      // uncomment below and update the code to test the property effectiveGasPrice
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property from (base name: "From")', function() {
      // uncomment below and update the code to test the property from
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property gasUsed (base name: "GasUsed")', function() {
      // uncomment below and update the code to test the property gasUsed
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property logs (base name: "Logs")', function() {
      // uncomment below and update the code to test the property logs
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property logsBloom (base name: "LogsBloom")', function() {
      // uncomment below and update the code to test the property logsBloom
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "To")', function() {
      // uncomment below and update the code to test the property to
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property transactionHash (base name: "TransactionHash")', function() {
      // uncomment below and update the code to test the property transactionHash
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property transactionIndex (base name: "TransactionIndex")', function() {
      // uncomment below and update the code to test the property transactionIndex
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "Type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new QanAutoApi.ResponseTransactionReceipt();
      //expect(instance).to.be();
    });

  });

}));
