/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QanAutoApi);
  }
}(this, function(expect, QanAutoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QanAutoApi.ResponseWithdrawals();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseWithdrawals', function() {
    it('should create an instance of ResponseWithdrawals', function() {
      // uncomment below and update the code to test ResponseWithdrawals
      //var instance = new QanAutoApi.ResponseWithdrawals();
      //expect(instance).to.be.a(QanAutoApi.ResponseWithdrawals);
    });

    it('should have the property address (base name: "Address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new QanAutoApi.ResponseWithdrawals();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "Amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new QanAutoApi.ResponseWithdrawals();
      //expect(instance).to.be();
    });

    it('should have the property index (base name: "Index")', function() {
      // uncomment below and update the code to test the property index
      //var instance = new QanAutoApi.ResponseWithdrawals();
      //expect(instance).to.be();
    });

    it('should have the property validatorIndex (base name: "ValidatorIndex")', function() {
      // uncomment below and update the code to test the property validatorIndex
      //var instance = new QanAutoApi.ResponseWithdrawals();
      //expect(instance).to.be();
    });

  });

}));
